# Generated by Django 3.0.8 on 2020-12-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_reminders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminders',
            name='body',
        ),
    ]
