# Generated by Django 3.0.8 on 2020-12-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='timestamp',
            field=models.DateTimeField(verbose_name='%b %#d %Y, %#I:%M %p'),
        ),
    ]
