# Generated by Django 3.0.8 on 2020-12-26 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20201218_1958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.AddField(
            model_name='entry',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='remindtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='subject',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
