# Generated by Django 3.0.8 on 2020-12-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_auto_20201226_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='reminder',
            new_name='isreminder',
        ),
    ]
