# Generated by Django 3.0.8 on 2020-12-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_auto_20201226_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='remindtime',
            field=models.DateTimeField(),
        ),
    ]
