# Generated by Django 3.0.8 on 2020-12-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_auto_20201226_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='remindtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
