# Generated by Django 3.0.8 on 2020-12-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20201226_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='remindtime',
        ),
    ]
