# Generated by Django 3.0.8 on 2020-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_remove_entry_remindtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='remindtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
