# Generated by Django 3.0.8 on 2020-12-29 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_sharedentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedentry',
            name='writer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
