# Generated by Django 3.0.8 on 2021-01-05 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_sharedentry_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='remindtime',
        ),
        migrations.CreateModel(
            name='Remind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remindtime', models.DateTimeField(blank=True, null=True)),
                ('isreminder', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remind', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
