# Generated by Django 3.0.8 on 2021-01-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_auto_20210104_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remind',
            name='timestamp',
        ),
    ]
